/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import javax.swing.JOptionPane;
/*
 * NewJFrame6.java
 *
 * Created on Nov 26, 2017, 2:21:38 AM
 */
/**
 *
 * @author dell
 */
public class NewJFrame6 extends javax.swing.JFrame {

    /** Creates new form NewJFrame6 */
    public NewJFrame6() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bodoni MT Black", 3, 24));
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("SEARCH INFORMATION OF A PRODUCT");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 10, 910, 56);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18));
        jLabel2.setForeground(new java.awt.Color(255, 204, 153));
        jLabel2.setText("ENTER PRODUCT_ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 110, 230, 26);

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 18));
        jButton1.setForeground(new java.awt.Color(51, 0, 51));
        jButton1.setText("FETCH INFORMATION");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 160, 290, 35);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(420, 120, 140, 20);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18));
        jLabel3.setForeground(new java.awt.Color(51, 0, 153));
        jLabel3.setText("PRODUCT NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 210, 190, 26);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 18));
        jLabel4.setForeground(new java.awt.Color(51, 0, 51));
        jLabel4.setText("PRICE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 300, 140, 26);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(430, 210, 130, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(430, 310, 130, 20);

        jButton2.setFont(new java.awt.Font("Arial Black", 1, 18));
        jButton2.setForeground(new java.awt.Color(153, 0, 0));
        jButton2.setText("CLOSE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(300, 370, 140, 35);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18));
        jLabel5.setForeground(new java.awt.Color(153, 0, 153));
        jLabel5.setText("PRODUCT_TYPE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 260, 200, 20);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(430, 260, 130, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kaffee-spezialitaeten.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 800, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
    Class.forName("java.sql.DriverManager");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/cafe","root","root");
    String product_id,sql;
    product_id=jTextField1.getText();

    sql="select* from product where product_id=" +product_id;
    Statement st=con.createStatement();
    ResultSet rs=st.executeQuery(sql);
    if(!rs.next())
    JOptionPane.showMessageDialog(this,"No Such Product");
    else{
        jTextField2.setText(rs.getString("product_name"));
        jTextField3.setText(rs.getString("price"));
        jTextField4.setText(rs.getString("product_type"));
    }
}
catch(Exception e){JOptionPane.showMessageDialog(this,"Error"+e.getMessage());}
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
NewJFrame2 f=new NewJFrame2();
f.show();
this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new NewJFrame6().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
