/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import javax.swing.JOptionPane;
/*
 * NewJFrame7.java
 *
 * Created on Nov 26, 2017, 2:36:40 AM
 */
/**
 *
 * @author dell
 */
public class NewJFrame7 extends javax.swing.JFrame {

    /** Creates new form NewJFrame7 */
    public NewJFrame7() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton2.setFont(new java.awt.Font("Arial Black", 1, 18));
        jButton2.setForeground(new java.awt.Color(0, 51, 51));
        jButton2.setText("CLOSE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(340, 470, 110, 35);

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 18));
        jButton1.setForeground(new java.awt.Color(0, 51, 51));
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 470, 100, 35);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(315, 229, 225, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(320, 140, 213, 20);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(315, 93, 213, 20);

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 36));
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("NEW MEMBERSHIP");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 20, 420, 33);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14));
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("CUSTOMER ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 96, 130, 21);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14));
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 140, 60, 21);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14));
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("EMAIL ID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 226, 80, 21);

        jLabel5.setFont(new java.awt.Font("Arial Black", 3, 24));
        jLabel5.setForeground(new java.awt.Color(204, 0, 102));
        jLabel5.setText("ENTER YOUR DETAILS HERE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 50, 430, 37);

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14));
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("GENDER");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 186, 80, 21);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jRadioButton1.setBackground(new java.awt.Color(153, 153, 255));
        jRadioButton1.setFont(new java.awt.Font("Arial", 1, 12));
        jRadioButton1.setText("MALE");
        jRadioButton1.setBorderPainted(true);
        jPanel1.add(jRadioButton1);

        jRadioButton2.setBackground(new java.awt.Color(255, 153, 153));
        jRadioButton2.setFont(new java.awt.Font("Arial", 1, 12));
        jRadioButton2.setText("FEMALE");
        jRadioButton2.setBorderPainted(true);
        jPanel1.add(jRadioButton2);

        jRadioButton3.setBackground(new java.awt.Color(204, 255, 204));
        jRadioButton3.setFont(new java.awt.Font("Arial", 1, 12));
        jRadioButton3.setText("OTHER");
        jRadioButton3.setBorderPainted(true);
        jPanel1.add(jRadioButton3);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(353, 186, 190, 25);

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 14));
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("ADDRESS");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 286, 90, 21);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(315, 274, 225, 96);

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 14));
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setText("PHONE NO.");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 401, 110, 21);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(315, 401, 225, 20);

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/The-River-Cafe-Chocolate-Brooklyn-Bridge-By-Chef-Brad-Steelman-022-2015.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 1080, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        NewJFrame2 f=new NewJFrame2();
        f.show();
        this.dispose();
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            Class.forName("java.sql.DriverManager");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/cafe","root","root");
            String customer_id,name,gender=" ",email_id,address,contact_no,sql;
            customer_id=jTextField1.getText();
            name=jTextField2.getText();
            if(jRadioButton1.isSelected())
                gender="male";
            else if(jRadioButton2.isSelected())
                gender="female";
            else if(jRadioButton3.isSelected())
                gender="other";
            email_id=jTextField3.getText();
            address=jTextArea1.getText();
            contact_no=jTextField4.getText();
            sql="insert into customer values("+customer_id+",'"+name+"','"+gender+"','"+email_id+"','"+address+"','"+contact_no+"')";
            Statement st=con.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(this,"new member saved");
        } catch(Exception e){JOptionPane.showMessageDialog(this,e.getMessage());}
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new NewJFrame7().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
