/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import javax.swing.JOptionPane;
/*
 * NewJFrame10.java
 *
 * Created on Nov 26, 2017, 2:39:52 AM
 */
/**
 *
 * @author dell
 */
public class NewJFrame10 extends javax.swing.JFrame {

    /** Creates new form NewJFrame10 */
    public NewJFrame10() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(378, 331, 225, 96);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jRadioButton1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(102, 51, 255));
        jRadioButton1.setText("MALE");
        jRadioButton1.setBorderPainted(true);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);

        jRadioButton2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 51, 51));
        jRadioButton2.setText("FEMALE");
        jRadioButton2.setBorderPainted(true);
        jPanel1.add(jRadioButton2);

        jRadioButton3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(0, 51, 0));
        jRadioButton3.setText("OTHER");
        jRadioButton3.setBorderPainted(true);
        jPanel1.add(jRadioButton3);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(393, 167, 240, 53);

        jButton2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 51));
        jButton2.setText("CLOSE");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(378, 494, 120, 31);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(390, 129, 213, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(378, 277, 225, 20);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 51));
        jLabel2.setText("CUSTOMER ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 140, 21);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(378, 445, 225, 20);

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 51));
        jLabel6.setText("GENDER");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 180, 80, 21);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(390, 54, 191, 20);

        jButton3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 51));
        jButton3.setText("FETCH DETAILS");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(197, 80, 240, 31);

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 51));
        jLabel8.setText("PHONE NO.");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 440, 120, 21);

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("SEARCH INFORMATION OF A MEMBER");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 33);

        jLabel5.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabel5.setText("ENTER YOUR NEW DETAILS HERE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 30, 440, 37);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 51));
        jLabel4.setText("EMAIL ID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 270, 90, 21);

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 51));
        jLabel7.setText("ADDRESS");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 330, 100, 21);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 51));
        jLabel3.setText("NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 130, 90, 21);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\New folder\\top-paddock.png")); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, -10, 730, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        NewJFrame2 f=new NewJFrame2();
        f.show();
        this.dispose();
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            Class.forName("java.sql.DriverManager");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/cafe","root","root");
            String customer_id,sql;
            customer_id=jTextField1.getText();
            
            sql="select* from customer where customer_id=" +customer_id;
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(sql);
            if(!rs.next())
                JOptionPane.showMessageDialog(this,"No Such Product");
            else{
                jTextField2.setText(rs.getString("name"));
                if(rs.getString("gender").equals("male"))
                    jRadioButton1.setSelected(true);
                else if(rs.getString("gender").equals("female"))
                    jRadioButton2.setSelected(true);
                else if(rs.getString("gender").equals("other"))
                    jRadioButton3.setSelected(true);
                
                jTextField3.setText(rs.getString("email_id"));
                jTextArea1.setText(rs.getString("address"));
                jTextField4.setText(rs.getString("contact_no"));
            }
        } catch(Exception e){JOptionPane.showMessageDialog(this,"Error"+e.getMessage());}
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new NewJFrame10().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
