/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * NewJFrame13.java
 *
 * Created on Nov 27, 2017, 1:50:48 AM
 */
/**
 *
 * @author dell
 */
public class NewJFrame13 extends javax.swing.JFrame {

    /** Creates new form NewJFrame13 */
    public NewJFrame13() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(330, 200, 234, 20);

        jButton3.setFont(new java.awt.Font("Arial Black", 1, 18));
        jButton3.setForeground(new java.awt.Color(102, 0, 102));
        jButton3.setText("FETCH DETAILS");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(170, 100, 230, 33);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 14));
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("NO_OF_MEMBERS");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(92, 238, 170, 21);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(330, 240, 234, 20);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14));
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 200, 60, 21);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14));
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("PHONE_NO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(92, 276, 110, 21);

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 36));
        jLabel1.setForeground(new java.awt.Color(208, 12, 54));
        jLabel1.setText("UPDATE A BOOKING");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 10, 370, 40);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14));
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("BOOKING_ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 60, 130, 21);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(327, 159, 234, 20);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(327, 65, 234, 20);

        jButton2.setFont(new java.awt.Font("Arial Black", 1, 18));
        jButton2.setForeground(new java.awt.Color(255, 0, 51));
        jButton2.setText("CLOSE");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(350, 420, 110, 33);

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 18));
        jButton1.setForeground(new java.awt.Color(255, 0, 51));
        jButton1.setText("UPDATE");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 420, 95, 33);

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14));
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("CUSTOMER_ID");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(92, 159, 130, 26);

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 14));
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("TIME");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(92, 308, 60, 21);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(327, 273, 234, 20);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(327, 311, 234, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\New folder\\embed-kirby-cafe-menu-item-2.jpg")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 670, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTextField2.setEditable(false);
        try{
            Class.forName("java.sql.DriverManager");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/cafe","root","root");
            String booking_id,sql;
            booking_id=jTextField1.getText();
            
            sql="select* from booking where booking_id=" +booking_id;
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(sql);
            if(!rs.next())
                JOptionPane.showMessageDialog(this,"No Such Booking");
            else{
                jTextField2.setText(rs.getString("customer_id"));
                jTextField3.setText(rs.getString("name"));
                jTextField4.setText(rs.getString("no"));
                jTextField5.setText(rs.getString("phone_no"));
                jTextField6.setText(rs.getString("Time"));
                
            }
        } catch(Exception e){JOptionPane.showMessageDialog(this,"Error"+e.getMessage());}
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        NewJFrame2 f=new NewJFrame2();
        f.show();
        this.dispose();
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            Class.forName("java.sql.DriverManager");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/cafe","root","root");
            String booking_id,customer_id,name,no,phone_no,time,sql;
            booking_id=jTextField1.getText();
            customer_id=jTextField2.getText();
            name=jTextField3.getText();
            no=jTextField4.getText();
            phone_no=jTextField5.getText();
            time=jTextField6.getText();
            
            sql="update booking set name='"+name+"',no="+no+",phone_no="+phone_no+",time='"+time+"' where booking_id="+booking_id;
            Statement st=con.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(this,"booking updated");
        } catch(Exception e){JOptionPane.showMessageDialog(this,e.getMessage());}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new NewJFrame13().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
