/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import javax.swing.JOptionPane;
/*
 * NewJFrame12.java
 *
 * Created on Nov 27, 2017, 1:25:21 AM
 */
/**
 *
 * @author dell
 */
public class NewJFrame12 extends javax.swing.JFrame {

    /** Creates new form NewJFrame12 */
    public NewJFrame12() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14));
        jLabel1.setForeground(new java.awt.Color(51, 0, 102));
        jLabel1.setText("CUSTOMER ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 124, 140, 21);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(484, 65, 194, 20);

        jLabel2.setFont(new java.awt.Font("Arial", 3, 18));
        jLabel2.setForeground(new java.awt.Color(255, 0, 102));
        jLabel2.setText("if not yet registered click here");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 170, 280, 17);

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Arial Black", 1, 18));
        jButton1.setForeground(new java.awt.Color(0, 51, 51));
        jButton1.setText("CLICK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(350, 170, 110, 35);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14));
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 212, 80, 21);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(484, 121, 194, 20);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14));
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("NO. OF MEMBERS");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 268, 160, 21);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 14));
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("PHONE NO");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 319, 110, 21);

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14));
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setText("TIME");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 373, 70, 21);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(484, 209, 194, 20);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(484, 265, 194, 20);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(484, 316, 194, 20);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 3, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 51));
        jLabel7.setText("BOOK A TABLE");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(250, 10, 280, 40);

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("Arial Black", 1, 18));
        jButton2.setForeground(new java.awt.Color(225, 17, 105));
        jButton2.setText("SUBMIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(167, 426, 160, 35);

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 14));
        jLabel8.setForeground(new java.awt.Color(51, 0, 102));
        jLabel8.setText("BOOKING ID");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(132, 68, 130, 21);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(484, 370, 194, 20);

        jButton3.setBackground(new java.awt.Color(255, 204, 204));
        jButton3.setFont(new java.awt.Font("Arial Black", 1, 18));
        jButton3.setForeground(new java.awt.Color(185, 27, 65));
        jButton3.setText("CLOSE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(480, 430, 110, 35);

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 14));
        jLabel9.setForeground(new java.awt.Color(102, 0, 102));
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\New folder\\March22.CafeCava2200.JPG")); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 10, 750, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
NewJFrame3 f=new NewJFrame3();
f.show();
this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try{
    Class.forName("java.sql.DriverManager");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/cafe","root","root");
    String booking_id,customer_id,name,no,phone_no,time,sql;
    booking_id=jTextField1.getText();
    customer_id=jTextField2.getText();
    name=jTextField3.getText();
    no=jTextField4.getText();
    phone_no=jTextField5.getText();
    time=jTextField6.getText();
    sql="insert into booking values("+booking_id+","+customer_id+",'"+name+"',"+no+","+phone_no+",'"+time+"')";
    Statement st=con.createStatement();
    st.executeUpdate(sql);
    JOptionPane.showMessageDialog(this,"booking saved");
}
catch(Exception e){JOptionPane.showMessageDialog(this,e.getMessage());}
                                
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
NewJFrame2 f=new NewJFrame2();
f.show();
this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new NewJFrame12().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
